"""initial schema - 27 tables

Revision ID: 074369ef0169
Revises: 
Create Date: 2026-02-05 22:02:20.207132
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074369ef0169'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('report_date_start', sa.Date(), nullable=True),
    sa.Column('report_date_end', sa.Date(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_logs_file_hash', 'import_logs', ['file_hash'], unique=False)
    op.create_table('inv_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('count_type', sa.String(length=20), nullable=False),
    sa.Column('counted_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('supply_categories', sa.String(length=500), nullable=True),
    sa.Column('delivery_days', sa.String(length=100), nullable=True),
    sa.Column('order_deadline_day', sa.String(length=20), nullable=True),
    sa.Column('order_deadline_time', sa.Time(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('invoice_format', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pos_daily_sales_by_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receipt_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_day', 'category_name', name='uq_category_day')
    )
    op.create_table('pos_daily_sales_by_daypart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('day_part', sa.String(length=50), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('checks', sa.Integer(), nullable=True),
    sa.Column('guest_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('check_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_day', 'day_part', name='uq_daypart_day')
    )
    op.create_table('pos_hourly_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('avg_check', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_day', 'hour_of_day', name='uq_hourly_day')
    )
    op.create_index('ix_hourly_sales_day', 'pos_hourly_sales', ['trading_day'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pos_item_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('yield_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_pos_item', 'recipes', ['pos_item_id'], unique=False)
    op.create_table('inv_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['inv_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'invoice_number', name='uq_invoice_vendor')
    )
    op.create_table('inv_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('bottle_size_ml', sa.Integer(), nullable=True),
    sa.Column('par_level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inventory_tier', sa.String(length=1), nullable=False),
    sa.Column('primary_vendor_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('case_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pos_item_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_vendor_id'], ['inv_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_items_category', 'inv_items', ['category'], unique=False)
    op.create_index('ix_inv_items_tier', 'inv_items', ['inventory_tier'], unique=False)
    op.create_table('pos_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_printer_group', sa.String(length=100), nullable=True),
    sa.Column('requires_position', sa.Boolean(), nullable=True),
    sa.Column('tax_type', sa.String(length=50), nullable=True),
    sa.Column('reset_stock_on_close', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('parent_category_id', sa.String(length=36), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['pos_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_number', sa.String(length=20), nullable=False),
    sa.Column('check_name', sa.String(length=200), nullable=True),
    sa.Column('server', sa.String(length=200), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('comps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voids', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auto_grat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bill_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tips_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_center', sa.String(length=100), nullable=True),
    sa.Column('trading_day', sa.Date(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_number', 'trading_day', 'opened_at', name='uq_check_day')
    )
    op.create_index('ix_checks_opened_at', 'pos_checks', ['opened_at'], unique=False)
    op.create_index('ix_checks_trading_day', 'pos_checks', ['trading_day'], unique=False)
    op.create_table('pos_comps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp_date', sa.DateTime(), nullable=True),
    sa.Column('comp_reason', sa.String(length=200), nullable=True),
    sa.Column('check_owner', sa.String(length=200), nullable=True),
    sa.Column('authorized_by', sa.String(length=200), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('comp_type', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('trading_day', sa.Date(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comps_trading_day', 'pos_comps', ['trading_day'], unique=False)
    op.create_table('pos_daily_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('total_receipts', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_without_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('liquor_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sales_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_on_comps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_guests', sa.Integer(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('guest_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('check_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_payments', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_payments', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_comps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_voids', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_day')
    )
    op.create_table('pos_display_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_timing', sa.String(length=10), nullable=True),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('repeat_days', sa.String(length=100), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('online_menu_name', sa.String(length=300), nullable=True),
    sa.Column('chit_name', sa.String(length=300), nullable=True),
    sa.Column('receipt_name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('online_menu_description', sa.Text(), nullable=True),
    sa.Column('sort_code', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.String(length=200), nullable=True),
    sa.Column('printer_group', sa.String(length=100), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('item_contains_alcohol', sa.Boolean(), nullable=True),
    sa.Column('course', sa.String(length=50), nullable=True),
    sa.Column('allow_price_override', sa.Boolean(), nullable=True),
    sa.Column('min_sides', sa.Integer(), nullable=True),
    sa.Column('max_sides', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reset_stock_on_close', sa.String(length=50), nullable=True),
    sa.Column('current_stock_level', sa.Integer(), nullable=True),
    sa.Column('reset_stock_value', sa.Integer(), nullable=True),
    sa.Column('modifier_groups_raw', sa.Text(), nullable=True),
    sa.Column('display_groups_raw', sa.Text(), nullable=True),
    sa.Column('item_identifier', sa.String(length=200), nullable=True),
    sa.Column('online_ordering_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('include_preorders_in_stock', sa.Boolean(), nullable=True),
    sa.Column('inventory_tier', sa.String(length=1), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pos_items_category', 'pos_items', ['category_name'], unique=False)
    op.create_table('pos_labor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('shift_start', sa.DateTime(), nullable=True),
    sa.Column('shift_end', sa.DateTime(), nullable=True),
    sa.Column('reg_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ot_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pay_per_hour', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('blended_pay_per_hour', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_pay', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trading_day', sa.Date(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'last_name', 'first_name', 'shift_date', 'shift_start', name='uq_labor_shift')
    )
    op.create_index('ix_labor_trading_day', 'pos_labor', ['trading_day'], unique=False)
    op.create_table('pos_modifier_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('print_on_ticket', sa.Boolean(), nullable=True),
    sa.Column('sort_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('min_selections', sa.Integer(), nullable=True),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_modifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('chit_name', sa.String(length=300), nullable=True),
    sa.Column('receipt_name', sa.String(length=300), nullable=True),
    sa.Column('sort_code', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('modifier_groups_raw', sa.Text(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tender_type', sa.String(length=50), nullable=True),
    sa.Column('tender_account', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('trading_day', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('server', sa.String(length=200), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_trading_day', 'pos_payments', ['trading_day'], unique=False)
    op.create_table('pos_product_mix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_start_date', sa.Date(), nullable=False),
    sa.Column('report_end_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('pos_item_id', sa.String(length=36), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('qty_sold', sa.Integer(), nullable=True),
    sa.Column('qty_void', sa.Integer(), nullable=True),
    sa.Column('qty_comp', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comp_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receipt_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('item_identifier', sa.String(length=200), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_start_date', 'report_end_date', 'entry_type', 'pos_item_id', name='uq_pmix_item_period')
    )
    op.create_index('ix_pmix_dates', 'pos_product_mix', ['report_start_date', 'report_end_date'], unique=False)
    op.create_index('ix_pmix_item_id', 'pos_product_mix', ['pos_item_id'], unique=False)
    op.create_table('pos_voids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('void_date', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.String(length=200), nullable=True),
    sa.Column('check_owner', sa.String(length=200), nullable=True),
    sa.Column('authorized_by', sa.String(length=200), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('trading_day', sa.Date(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voids_trading_day', 'pos_voids', ['trading_day'], unique=False)
    op.create_table('inv_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inv_item_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inv_item_id'], ['inv_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adjustments_date', 'inv_adjustments', ['adjustment_date'], unique=False)
    op.create_table('inv_count_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('inv_item_id', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('theoretical_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variance_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['count_id'], ['inv_counts.id'], ),
    sa.ForeignKeyConstraint(['inv_item_id'], ['inv_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_daily_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inv_item_id', sa.Integer(), nullable=False),
    sa.Column('ledger_date', sa.Date(), nullable=False),
    sa.Column('opening_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchases_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('theoretical_usage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adjustments_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closing_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_of_cover', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('reorder_alert', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inv_item_id'], ['inv_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inv_item_id', 'ledger_date', name='uq_ledger_item_day')
    )
    op.create_index('ix_ledger_date', 'inv_daily_ledger', ['ledger_date'], unique=False)
    op.create_table('inv_invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('inv_item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extended_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inv_item_id'], ['inv_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['inv_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_item_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_item_id', sa.String(length=36), nullable=False),
    sa.Column('old_item_name', sa.String(length=300), nullable=False),
    sa.Column('new_item_id', sa.String(length=36), nullable=True),
    sa.Column('new_item_name', sa.String(length=300), nullable=True),
    sa.Column('alias_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_item_id'], ['pos_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pos_item_aliases_old_id', 'pos_item_aliases', ['old_item_id'], unique=False)
    op.create_table('recipe_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('inv_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('waste_factor', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inv_item_id'], ['inv_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_lines')
    op.drop_index('ix_pos_item_aliases_old_id', table_name='pos_item_aliases')
    op.drop_table('pos_item_aliases')
    op.drop_table('inv_invoice_lines')
    op.drop_index('ix_ledger_date', table_name='inv_daily_ledger')
    op.drop_table('inv_daily_ledger')
    op.drop_table('inv_count_lines')
    op.drop_index('ix_adjustments_date', table_name='inv_adjustments')
    op.drop_table('inv_adjustments')
    op.drop_index('ix_voids_trading_day', table_name='pos_voids')
    op.drop_table('pos_voids')
    op.drop_index('ix_pmix_item_id', table_name='pos_product_mix')
    op.drop_index('ix_pmix_dates', table_name='pos_product_mix')
    op.drop_table('pos_product_mix')
    op.drop_index('ix_payments_trading_day', table_name='pos_payments')
    op.drop_table('pos_payments')
    op.drop_table('pos_modifiers')
    op.drop_table('pos_modifier_groups')
    op.drop_index('ix_labor_trading_day', table_name='pos_labor')
    op.drop_table('pos_labor')
    op.drop_index('ix_pos_items_category', table_name='pos_items')
    op.drop_table('pos_items')
    op.drop_table('pos_display_groups')
    op.drop_table('pos_daily_sales')
    op.drop_index('ix_comps_trading_day', table_name='pos_comps')
    op.drop_table('pos_comps')
    op.drop_index('ix_checks_trading_day', table_name='pos_checks')
    op.drop_index('ix_checks_opened_at', table_name='pos_checks')
    op.drop_table('pos_checks')
    op.drop_table('pos_categories')
    op.drop_index('ix_inv_items_tier', table_name='inv_items')
    op.drop_index('ix_inv_items_category', table_name='inv_items')
    op.drop_table('inv_items')
    op.drop_table('inv_invoices')
    op.drop_index('ix_recipes_pos_item', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('ix_hourly_sales_day', table_name='pos_hourly_sales')
    op.drop_table('pos_hourly_sales')
    op.drop_table('pos_daily_sales_by_daypart')
    op.drop_table('pos_daily_sales_by_category')
    op.drop_table('inv_vendors')
    op.drop_table('inv_counts')
    op.drop_index('ix_import_logs_file_hash', table_name='import_logs')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
