"""fix check unique constraint for split checks

Revision ID: 4de1de2fdaf7
Revises: 074369ef0169
Create Date: 2026-02-05 22:03:44.877862
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de1de2fdaf7'
down_revision: Union[str, None] = '074369ef0169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_check_day'), 'pos_checks', type_='unique')
    op.create_unique_constraint('uq_check_day', 'pos_checks', ['check_number', 'trading_day', 'opened_at', 'check_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_check_day', 'pos_checks', type_='unique')
    op.create_unique_constraint(op.f('uq_check_day'), 'pos_checks', ['check_number', 'trading_day', 'opened_at'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
