"""add operational expenses and owner distributions

Revision ID: 5ef8f58f8b70
Revises: a783d84b375f
Create Date: 2026-02-07 01:01:57.275591
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef8f58f8b70'
down_revision: Union[str, None] = 'a783d84b375f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_expense_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typical_frequency', sa.String(length=20), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('owner_distributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distribution_date', sa.Date(), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distribution_type', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_distributions_date', 'owner_distributions', ['distribution_date'], unique=False)
    op.create_table('op_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_category_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_category_id'], ['op_expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_op_expenses_category', 'op_expenses', ['expense_category_id'], unique=False)
    op.create_index('ix_op_expenses_date', 'op_expenses', ['expense_date'], unique=False)
    op.create_index('ix_op_expenses_period', 'op_expenses', ['period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_op_expenses_period', table_name='op_expenses')
    op.drop_index('ix_op_expenses_date', table_name='op_expenses')
    op.drop_index('ix_op_expenses_category', table_name='op_expenses')
    op.drop_table('op_expenses')
    op.drop_index('ix_distributions_date', table_name='owner_distributions')
    op.drop_table('owner_distributions')
    op.drop_table('op_expense_categories')
    # ### end Alembic commands ###
