"""add item_name to product mix unique constraint

Revision ID: a783d84b375f
Revises: 4de1de2fdaf7
Create Date: 2026-02-05 22:04:48.889636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a783d84b375f'
down_revision: Union[str, None] = '4de1de2fdaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_pmix_item_period'), 'pos_product_mix', type_='unique')
    op.create_unique_constraint('uq_pmix_item_period', 'pos_product_mix', ['report_start_date', 'report_end_date', 'entry_type', 'pos_item_id', 'item_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pmix_item_period', 'pos_product_mix', type_='unique')
    op.create_unique_constraint(op.f('uq_pmix_item_period'), 'pos_product_mix', ['report_start_date', 'report_end_date', 'entry_type', 'pos_item_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
