"""add recurring expenses table and link to op_expenses

Revision ID: af24cf8c6811
Revises: b8a1c2d3e4f5
Create Date: 2026-02-08 17:31:36.656715
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af24cf8c6811'
down_revision: Union[str, None] = 'b8a1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_category_id'], ['op_expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_expenses_category', 'recurring_expenses', ['expense_category_id'], unique=False)
    op.add_column('op_expenses', sa.Column('recurring_expense_id', sa.Integer(), nullable=True))
    op.create_index('ix_op_expenses_recurring', 'op_expenses', ['recurring_expense_id'], unique=False)
    op.create_foreign_key(None, 'op_expenses', 'recurring_expenses', ['recurring_expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'op_expenses', type_='foreignkey')
    op.drop_index('ix_op_expenses_recurring', table_name='op_expenses')
    op.drop_column('op_expenses', 'recurring_expense_id')
    op.drop_index('ix_recurring_expenses_category', table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
